version: "3.7"
services:
  # postgres:
  #   image: postgres:latest
  #   networks:
  #     - postgres
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - postgres:/data/postgres
  #   environment:
  #     - POSTGRES_USER=$POSTGRES_DB
  #     - POSTGRES_PASSWORD=$POSTGRES_DB_PASSWORD
  #     - POSTGRES_DB=$POSTGRES_DB

  # pgadmin:
  #   image: dpage/pgadmin4:6.18
  #   networks:
  #     - postgres
  #   ports:
  #     - "8080:80"
  #   volumes:
  #     - pgadmin-data:/var/lib/pgadmin
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=$PGADMIN_EMAIL
  #     - PGADMIN_DEFAULT_PASSWORD=$PGADMIN_PASSWORD

  nestjs-api:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "6001:3000"

# networks:
#   postgres:
#     driver: bridge

# volumes:
#   postgres:
#   pgadmin-data:
